language: android

notifications:
  email: false

android:
  components:
    - tools
    - platform-tools
    - android-28

before_install:
  - chmod +x gradlew

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

script:
  - ./gradlew build
  
branches:
  only:
    - master
  
