language: android

android:
  components:
    - platform-tools
    - android-28

before_install:
  - chmod +x gradlew
  - yes | sudo sdkmanager --licenses

script:
  - ./gradlew build
  
branches:
  only:
    - master
  
