language: android

notifications:
  email: false

android:
  components:
    - tools
    - platform-tools
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

before_install:
  - chmod +x gradlew
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;27.0.3"

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

script:
  - ./gradlew build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
branches:
  only:
    - master


  
